### PR TITLE
Town development

### PR DESCRIPTION
**Pull request by defritz**
Finalizing town and laying UI groundwork functionality

### CODE REVIEW

**Comment by joyellealina** [comment]
Just fix the conflicts, and this is good to merge. The conflicts should be small fixes.

**Comment by defritz** [comment]
There's 116 conflicts in Main, not sure if there's a faster way to resolve them rather than going through and deleting the old code.

**Comment by joyellealina** [comment]
I may have fixed the conflicts? I may just merge it and if anything looks off we can just fix it since it's only terrain and environment objects.

**Comment by joyellealina** [comment]
Actually scratch that, it looks all fucked up now.

**Comment by defritz** [comment]
I added UI stuff too, not just messing with terrain and prefabs. Could we just replace the master branch with this branch? I don't see anything added to master other than readme edits.

**Comment by joyellealina** [comment]
Yeah, I fixed it. Had to do some janky stuff, but it's all good to go now. Gonna go ahead and merge.

**Pull request merged**
